### PR TITLE
track CM's system/netd to fix "Portable Wi-Fi hotspot"

### PR DESCRIPTION
**Pull request by alteredlikeness**
(and removed an extra space..)

### CODE REVIEW

**Comment by slickrick** [comment]
Does CM system/netd need any commits in any other repos?

**Comment by alteredlikeness** [comment]
No.. I've had no problems using it in 4.3 and 4.2.2.. But, you can call it temporary if you wish, and I will try to hunt down what is breaking the wifi hotspot in some devices. Is it broken in only some legacy devices, or all?

**Comment by slickrick** [comment]
Yea hotspot is working fine on my note 2 and probably all other smdk4412 devices. If it fixes a few things for your device and doesn't break anything I don't mind merging.

**Comment by alteredlikeness** [comment]
Yea, it may be motorola and/or ti omap specific (fixes it in Atrix 2 and the xt910/912 RAZRs at least), but shouldn't break anything for others...

**Comment by alteredlikeness** [comment]
Just had a second thought... I also have CM's hardware/ti's (omap4xxx, wlan, and wpan).. Can someone else confirm this doesn't break build without those, please? I can't run a test build for a little while..

**Pull request merged**
