### PR TITLE
broken repo 

### PR DESCRIPTION
**Pull request by percy-g2**

### CODE REVIEW

**Comment by axsddlr** [comment]
We dont maintain 4.2.2 builds anymore. Make appropriate changes to your own fork

**Comment by percy-g2** [comment]
was trying to help noobs .NVM

**Comment by axsddlr** [comment]
noobs should be using latest repos not old 4.2.2/jellybean ones......

**Comment by percy-g2** [comment]
delete them :-1:

**Comment by SferaDev** [comment]
@percy-g2 We will delete everything with KitKat, don't worry. We will kill Jelly Bean with Fire, xD!

**Pull request closed without merging**
